# Generated by Django 3.1.6 on 2021-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210228_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
